Product/Product/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('basic_app/', include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

Product/basic_app/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'

urlpatterns = [
	path('list/', views.ProductListView.as_view(), name='product_list'),
	path('details/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
	path('create/', views.ProductCreateView.as_view(), name='product_create'),
	path('update/<int:pk>/', views.ProductUpdateView.as_view(), name='product_update'),
	path('delete/<int:pk>/', views.ProductDeleteView.as_view(), name='product_delete'),
]

Product/basic_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Product(models.Model):
	Name = models.CharField(max_length=256)
	Company = models.CharField(max_length=256)
	Published = models.DateField()
	Price = models.PositiveIntegerField()

	def __str__(self):
		return self.Name

	def get_absolute_url(self):
		return reverse('basic_app:product_detail', kwargs={'pk':self.pk})

Product/basic_app/views.py
from django.shortcuts import render
from . import models
from django.views.generic import (TemplateView, ListView, DetailView,
								CreateView, UpdateView, DeleteView)
from django.urls import reverse_lazy
# Create your views here.

class HomeView(TemplateView):
	template_name = 'Home.html'

class ProductListView(ListView):
	model = models.Product

class ProductDetailView(DetailView):
	model = models.Product

class ProductCreateView(CreateView):
	fields = '__all__'
	model = models.Product

class ProductUpdateView(UpdateView):
	fields = ['Name', 'Company', 'Price']
	model = models.Product

class ProductDeleteView(DeleteView):
	model = models.Product
	success_url = reverse_lazy('basic_app:product_list')

Product/basic_app/templates/basic_app/app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Product</title>
</head>
<body>
	<nav>
		<ul>
			<li><a href="{% url 'home' %}">Home</a></li>
			<li><a href="{% url 'basic_app:product_list' %}">Products</a></li>
		</ul>
	</nav>

	{% block __body__ %}
		<!-- contents -->
	{% endblock __body__ %}
</body>
</html>

Product/basic_app/templates/basic_app/product_confirm_delete.html
{% extends "basic_app/app_base.html" %}

{% block __body__ %}

	<h1>Confirm Delete {{product.Name}}?</h1>

	<form method="post">
		{% csrf_token %}
		<input type="submit" value="Delete">
		<a href="{% url 'basic_app:product_detail' pk=product.pk %}">Cancel</a>
	</form>

{% endblock __body__ %}

Product/basic_app/templates/basic_app/product_detail.html
{% extends "basic_app/app_base.html" %}

{% block __body__ %}

	<h1>Details for {{product.Name}}:</h1>
	<p>Name: {{product.Name}}</p>
	<p>Company: {{product.Company}}</p>
	<p>Published: {{product.Published}}</p>
	<p>Price: {{product.Price}}$</p>

	<h2><a href="{% url 'basic_app:product_update' pk=product.pk %}">Update Product</a></h2>
	<h2><a href="{% url 'basic_app:product_delete' pk=product.pk %}">Delete Product</a></h2>

{% endblock __body__ %}

Product/basic_app/templates/basic_app/product_form.html
{% extends "basic_app/app_base.html" %}

{% block __body__ %}

	{% if form.instance.pk %}
		<h1>Update Product:</h1>
	{% else %}
		<h1>Create Product:</h1>
	{% endif %}

	<form method="post">
		{% csrf_token %}
		{{form.as_p}}
		
		{% if form.instance.pk %}
			<input type="submit" value="Update">
		{% else %}
			<input type="submit" value="Create">
		{% endif %}

	</form>

{% endblock __body__ %}

Product/basic_app/templates/basic_app/product_list.html
{% extends 'basic_app/app_base.html' %}

{% block __body__ %}

	<h1>Products List:</h1>

	{% if product_list %}
		<ol>
			{% for product in product_list %}
				<a href="{% url 'basic_app:product_detail' pk=product.id %}"><li><p>{{product.Name}}</p></li></a>
			{% endfor %}
		</ol>
	{% else %}
		<h3>No Products!</h3>
	{% endif %}

	<h2><a href="{% url 'basic_app:product_create' %}">Create Product</a></h2>

{% endblock __body__ %}

Product/templates/Base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Product</title>
</head>
<body>
	<nav>
		<ul>
			<li><a href="{% url 'home' %}">Home</a></li>
			<li><a href="{% url 'basic_app:product_list' %}">Products</a></li>
		</ul>
	</nav>

	{% block __body__ %}
		<!-- contents -->
	{% endblock __body__ %}
</body>
</html>

Product/templates/Home.html
{% extends "Base.html" %}

{% block __body__ %}
	<h1>Welcome to Home Page</h1>
	<h3>Go to Products Menu to see the Products</h3>
{% endblock __body__ %}